services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "5353:53/tcp"  # Map Windows 5353 to Container 53
      - "5353:53/udp"
      - "80:80/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_TIME
    environment:
      - TZ=America/New_York
      - FTLCONF_dns_listeningMode=all
      - FTLCONF_dns_upstreams=8.8.8.8
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      - './var-log-pihole:/var/log/pihole'
    restart: unless-stopped